#/bin/bash

# Work with arguments
# Read file with awk
awk '{print $0}' < $1


UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
